#!/bin/sh
echo Starting Webmin server in /opt/webmin
trap '' 1
LANG=
export LANG
#PERLIO=:raw
unset PERLIO
export PERLIO
PERLLIB=/opt/webmin
export PERLLIB
exec '/opt/webmin/miniserv.pl' $* /etc/webmin/miniserv.conf
